# -*- coding: utf-8 -*-
"""Conv For Sentence Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zuYFfcbA4rHf86pI3BCpBJZ4i1ma9bnn

Sentence Classification Examples:

    1. Sentiment Analysis
        1.1 Positive
        1.2 Negative
        I really hate this music -> Negative -> 0
        I love this food -> Positive -> 1
    2. Jumla qaysi tilda yozilganini aniqlash
    3. Names dataset classification
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install unidecode

import torch
from google.colab import drive

drive.mount("/drive")

from unidecode import unidecode

!ls /drive/MyDrive/data/names

import os
from glob import glob

root_dir = "/drive/MyDrive/data/names"
file_names = glob("*.txt", root_dir=root_dir)
unique_labels = sorted([os.path.splitext(file_name)[0] for file_name in file_names])
n_labels = len(unique_labels)

idx2label = {idx:label for idx, label in enumerate(unique_labels)}
label2idx = {label:idx for idx, label in idx2label.items()}

def replace(name, chars, target):
    for char in chars:
        name = name.replace(char, target)
    return name

X_names = []
Y_labels = []

for file_name in file_names:
    with open(os.path.join(root_dir, file_name), "rt", encoding='utf-8') as f:
        for line in f:
            name = line.strip().lower()
            name = unidecode(name)

            if name == 'to the first page':
                continue

            name = replace(name, [",", '1', "/b", ":", "\xa0"], '')
            name = replace(name, ['-'], ' ')

            X_names.append(name)
            Y_labels.append(os.path.splitext(file_name)[0])

"""1. Remove "To The First Page" names from dataset
2. Replace ",", '1', "/B", ":", \xa0 with empty string
3. Replace '-' with ' '
4. Convert all the following from unicode to ascii:
[ 'ß',
 'à',
 'á',
 'ã',
 'ä',
 'ç',
 'è',
 'é',
 'ê',
 'ì',
 'í',
 'ñ',
 'ò',
 'ó',
 'õ',
 'ö',
 'ù',
 'ú',
 'ü',
 'ą',
 'ł',
 'ń',
 'ś',
 'ż']
"""

pad_token = '.'
pad_token_id = 0

unique_chars = [pad_token] + sorted(set(''.join(X_names)))
idx2char = {idx:char for idx, char in enumerate(unique_chars)}
char2idx = {char:idx for idx, char in idx2char.items()}

def encode(name: str) -> list[int]:
    return [char2idx[char] for char in name]

def decode(ids: list[int]) -> str:
    return ''.join(idx2char[i] for i in ids)

Y = [label2idx[label] for label in Y_labels]
X = [encode(name) for name in X_names]

for x, x_name, y, y_label in zip(X[:5], X_names[:5], Y[:5], Y_labels[:5]):
    print(f"{str(x):<35} -> {x_name:<10} {y} -> {y_label}")

"""1. Split data into train and test
2. NamesDataset for both train and test
3. Data Loader for both train and test with custom `collate` function
"""

from sklearn.model_selection import  train_test_split

Xtr, Xts, Ytr, Yts = train_test_split(X, Y, test_size=0.2, stratify=Y)

from torch.utils.data import Dataset, DataLoader

class NamesDataset(Dataset):
    def __init__(self, X, Y):
        self.X = X
        self.Y = Y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]

Dtr = NamesDataset(Xtr, Ytr)
Dts = NamesDataset(Xts, Yts)

global_max_n = 20

def collate_fn(batch):
    # print(batch)
    x, y = zip(*batch)
    max_n = max(len(row) for row in x)
    max_n = global_max_n if max_n > global_max_n else max_n
    x_padded = torch.zeros(len(x), max_n, dtype=torch.long)

    for i in range(len(x)):
        x_padded[i, :len(x[i])] = torch.tensor(x[i][:max_n])

    return x_padded, torch.tensor(y, dtype=torch.long)


Dltr = DataLoader(Dtr, batch_size=4, shuffle=True, drop_last=True, collate_fn=collate_fn)
Dlts = DataLoader(Dts, batch_size=4, shuffle=False, drop_last=False, collate_fn=collate_fn)

idx2label

# Define Model
import torch
import torch.nn as nn
import torch.nn.functional as F
from dataclasses import dataclass

class  NamesClassifier(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.emb = nn.Embedding(self.config.vocab_size, self.config.n_embd) # B, T, C
        self.conv = nn.Conv1d(self.config.n_embd, self.config.n_conv_channels, self.config.kernel_size)

        self.max_pool = nn.AdaptiveMaxPool1d(1)
        self.drop = nn.Dropout(self.config.drop_rate)
        self.fc = nn.Linear(self.config.n_conv_channels, self.config.n_labels)

    def forward(self, x):
        x = self.emb(x)
        x = x.permute(0, 2, 1)
        x = self.conv(x)
        x = self.max_pool(x)
        x = self.drop(x.squeeze())
        x = self.fc(x)
        return x

@dataclass
class Config:
    vocab_size: int
    n_embd: int
    n_conv_channels: int
    kernel_size: int
    drop_rate: float
    n_labels: int

config = Config(vocab_size=29, n_embd=16, n_conv_channels=32, kernel_size=3, drop_rate=0.5, n_labels=18)
model = NamesClassifier(config)

model

# training loop
n_epochs = 3

for epoch in range(1, n_epochs+1):
    for x, y in Dltr:
        # take x and feed it to the model (not defined yet)
        logits = model(x)
        loss = F.cross_entropy(logits, y)
    # evaluate
    break
    # save the best model

accuracy, confusion matrix

logits = model(x)

logits[0]

F.softmax(logits[0], dim=0)

F.softmax(logits[0], dim=0).argmax()

F.softmax(logits[0], dim=0).shape

logits[0].argmax()

